# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_trnsctn.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 436)
        Dialog.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("border: 1 px solid rgba(255, 85, 255, 35);\n"
"border-radius: 8px;\n"
"background-color: rgba(170, 85, 255, 150);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 85, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.cbox_select_ctgry = QtWidgets.QComboBox(self.frame)
        self.cbox_select_ctgry.setStyleSheet("QComboBox {\n"
"color: rgb(0, 255, 255);\n"
"background-color: rgb(255, 0, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"padding-left: 15px;\n"
"}\n"
"\n"
"QComboBox:item {\n"
"color: rgb(0, 170, 255);\n"
"background-color: rgb(255, 0, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"padding-left: 15px;\n"
"}\n"
"\n"
"")
        self.cbox_select_ctgry.setObjectName("cbox_select_ctgry")
        self.cbox_select_ctgry.addItem("")
        self.cbox_select_ctgry.addItem("")
        self.cbox_select_ctgry.addItem("")
        self.cbox_select_ctgry.addItem("")
        self.verticalLayout_2.addWidget(self.cbox_select_ctgry)
        self.de_date = QtWidgets.QDateEdit(self.frame)
        self.de_date.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(255, 0, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"padding-left: 15px;")
        self.de_date.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.de_date.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.de_date.setDate(QtCore.QDate(2023, 1, 1))
        self.de_date.setObjectName("de_date")
        self.verticalLayout_2.addWidget(self.de_date)
        self.le_dscribe = QtWidgets.QLineEdit(self.frame)
        self.le_dscribe.setStyleSheet("color: rgb(255, 0, 255);\n"
"background-color: rgba(0, 255, 255, 150);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"padding-left: 15px;")
        self.le_dscribe.setObjectName("le_dscribe")
        self.verticalLayout_2.addWidget(self.le_dscribe)
        self.le_blnce = QtWidgets.QLineEdit(self.frame)
        self.le_blnce.setStyleSheet("color: rgb(255, 0, 255);\n"
"background-color: rgba(0, 255, 255, 150);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"padding-left: 15px;")
        self.le_blnce.setObjectName("le_blnce")
        self.verticalLayout_2.addWidget(self.le_blnce)
        self.select_up_or_down = QtWidgets.QComboBox(self.frame)
        self.select_up_or_down.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(255, 0, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"padding-left: 15px;")
        self.select_up_or_down.setObjectName("select_up_or_down")
        self.select_up_or_down.addItem("")
        self.select_up_or_down.addItem("")
        self.verticalLayout_2.addWidget(self.select_up_or_down)
        self.btn_save_trnsctn = QtWidgets.QPushButton(self.frame)
        self.btn_save_trnsctn.setStyleSheet("QPushButton {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 85, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid rgb(200, 0, 245);\n"
"border-radius: 7px;\n"
"width: 200 px;\n"
"height: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(170, 85, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(170, 85, 255, 65);\n"
"}")
        self.btn_save_trnsctn.setObjectName("btn_save_trnsctn")
        self.verticalLayout_2.addWidget(self.btn_save_trnsctn)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        self.cbox_select_ctgry.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "newTrnsctn"))
        self.label.setText(_translate("Dialog", "Добавить транзакцию"))
        self.cbox_select_ctgry.setCurrentText(_translate("Dialog", "Кредиты, налоги"))
        self.cbox_select_ctgry.setItemText(0, _translate("Dialog", "Кредиты, налоги"))
        self.cbox_select_ctgry.setItemText(1, _translate("Dialog", "Продукты питания, промтовары, одежда"))
        self.cbox_select_ctgry.setItemText(2, _translate("Dialog", "Транспорт"))
        self.cbox_select_ctgry.setItemText(3, _translate("Dialog", "Другое(досуг и т.д.)"))
        self.le_dscribe.setPlaceholderText(_translate("Dialog", "Описание"))
        self.le_blnce.setPlaceholderText(_translate("Dialog", "Баланс"))
        self.select_up_or_down.setItemText(0, _translate("Dialog", "Доход"))
        self.select_up_or_down.setItemText(1, _translate("Dialog", "Расход(затраты)"))
        self.btn_save_trnsctn.setText(_translate("Dialog", "Сохранить"))
