# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glav.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_glav(object):
    def setupUi(self, glav):
        glav.setObjectName("glav")
        glav.setEnabled(True)
        glav.resize(813, 584)
        glav.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.centralwidget = QtWidgets.QWidget(glav)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 25pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.all = QtWidgets.QFrame(self.centralwidget)
        self.all.setStyleSheet("border: 1px solid rgb(255, 85, 255);")
        self.all.setObjectName("all")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.all)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.balance_1 = QtWidgets.QFrame(self.all)
        self.balance_1.setStyleSheet("border: 1 px solid rgba(255, 85, 255, 35);\n"
"border-radius: 8px;")
        self.balance_1.setObjectName("balance_1")
        self.balance = QtWidgets.QVBoxLayout(self.balance_1)
        self.balance.setObjectName("balance")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.balance_1)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(200, 0, 235);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.balance_all = QtWidgets.QLabel(self.balance_1)
        self.balance_all.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 24pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.balance_all.setAlignment(QtCore.Qt.AlignCenter)
        self.balance_all.setObjectName("balance_all")
        self.verticalLayout.addWidget(self.balance_all)
        self.balance.addLayout(self.verticalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.balance_1)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(200, 0, 235);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.balance_1)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(200, 0, 235);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.up_blnc = QtWidgets.QLabel(self.balance_1)
        self.up_blnc.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.up_blnc.setAlignment(QtCore.Qt.AlignCenter)
        self.up_blnc.setObjectName("up_blnc")
        self.gridLayout_2.addWidget(self.up_blnc, 2, 0, 1, 1)
        self.down_blnc = QtWidgets.QLabel(self.balance_1)
        self.down_blnc.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.down_blnc.setAlignment(QtCore.Qt.AlignCenter)
        self.down_blnc.setObjectName("down_blnc")
        self.gridLayout_2.addWidget(self.down_blnc, 2, 1, 1, 1)
        self.balance.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.balance_1)
        self.expense = QtWidgets.QFrame(self.all)
        self.expense.setStyleSheet("border: 1 px solid rgba(255, 85, 255, 35);\n"
"border-radius: 8px;")
        self.expense.setObjectName("expense")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.expense)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.expense)
        self.label_8.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(200, 0, 235);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.transport_blnc = QtWidgets.QLabel(self.expense)
        self.transport_blnc.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.transport_blnc.setObjectName("transport_blnc")
        self.gridLayout_3.addWidget(self.transport_blnc, 2, 1, 1, 1)
        self.other_blnc = QtWidgets.QLabel(self.expense)
        self.other_blnc.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.other_blnc.setObjectName("other_blnc")
        self.gridLayout_3.addWidget(self.other_blnc, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.expense)
        self.label_12.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: rgb(200, 0, 245);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.grsries_clothes_blnc = QtWidgets.QLabel(self.expense)
        self.grsries_clothes_blnc.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.grsries_clothes_blnc.setObjectName("grsries_clothes_blnc")
        self.gridLayout_3.addWidget(self.grsries_clothes_blnc, 1, 1, 1, 1)
        self.credit_expense = QtWidgets.QLabel(self.expense)
        self.credit_expense.setMaximumSize(QtCore.QSize(100, 16777215))
        self.credit_expense.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.credit_expense.setObjectName("credit_expense")
        self.gridLayout_3.addWidget(self.credit_expense, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.expense)
        self.label_11.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: rgb(200, 0, 245);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.expense)
        self.label_9.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: rgb(200, 0, 245);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.expense)
        self.label_10.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: rgb(200, 0, 245);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout.addWidget(self.expense)
        self.verticalLayout_4.addWidget(self.all)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(200, 0, 215);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"border: none;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_add_trnsctn = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_trnsctn.setStyleSheet("QPushButton {\n"
"color: rgb(0, 255, 255);\n"
"background-color: rgb(200, 0, 235);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid rgb(200, 0, 245);\n"
"border-radius: 7px;\n"
"width: 200 px;\n"
"height: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(255, 129, 245);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(200, 0, 245, 65);\n"
"}")
        self.btn_add_trnsctn.setObjectName("btn_add_trnsctn")
        self.horizontalLayout_2.addWidget(self.btn_add_trnsctn)
        self.btn_remove_trnsctn = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remove_trnsctn.setStyleSheet("QPushButton {\n"
"color: rgb(0, 255, 255);\n"
"background-color: rgb(200, 0, 235);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid rgb(200, 0, 245);\n"
"border-radius: 7px;\n"
"width: 200 px;\n"
"height: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(255, 129, 245);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(200, 0, 245, 65);\n"
"}")
        self.btn_remove_trnsctn.setObjectName("btn_remove_trnsctn")
        self.horizontalLayout_2.addWidget(self.btn_remove_trnsctn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setStyleSheet("QTableView {\n"
"background-color: rgba(0, 255, 255, 25);\n"
"border: 1px solid rgba(0, 255, 255, 50);\n"
"border-bottom-right-radius: 8px;\n"
"border-bottom-left-radius: 8px;\n"
"}\n"
"\n"
"QTableView: section {\n"
"background-color: rgb(0, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"border: none;\n"
"height: 45px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QTableView: item {\n"
"border-style: none;\n"
"border-bottom: rgba(0, 255, 255, 45);\n"
"}\n"
"\n"
"QTableView: item:selected {\n"
"border: none;\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgba(0, 255, 255, 45);\n"
"}")
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setShowGrid(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(133)
        self.tableView.horizontalHeader().setMinimumSectionSize(43)
        self.verticalLayout_7.addWidget(self.tableView)
        glav.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(glav)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 22))
        self.menubar.setObjectName("menubar")
        glav.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(glav)
        self.statusbar.setObjectName("statusbar")
        glav.setStatusBar(self.statusbar)

        self.retranslateUi(glav)
        QtCore.QMetaObject.connectSlotsByName(glav)

    def retranslateUi(self, glav):
        _translate = QtCore.QCoreApplication.translate
        glav.setWindowTitle(_translate("glav", "expense analyzer"))
        self.label_2.setText(_translate("glav", "Добро пожаловать!"))
        self.label_3.setText(_translate("glav", "Баланс:"))
        self.balance_all.setText(_translate("glav", "11"))
        self.label_6.setText(_translate("glav", "Доход:"))
        self.label_4.setText(_translate("glav", "Расход:"))
        self.up_blnc.setText(_translate("glav", "11"))
        self.down_blnc.setText(_translate("glav", "11"))
        self.label_8.setText(_translate("glav", "Категории расходов:"))
        self.transport_blnc.setText(_translate("glav", "11"))
        self.other_blnc.setText(_translate("glav", "11"))
        self.label_12.setText(_translate("glav", "Другое (досуг и т.д.)"))
        self.grsries_clothes_blnc.setText(_translate("glav", "11"))
        self.credit_expense.setText(_translate("glav", "11"))
        self.label_11.setText(_translate("glav", "Транспорт"))
        self.label_9.setText(_translate("glav", "Кредиты, налоги"))
        self.label_10.setText(_translate("glav", "Продукты питания, промтовары, одежда"))
        self.label_17.setText(_translate("glav", "Транзакция"))
        self.btn_add_trnsctn.setText(_translate("glav", "Новая"))
        self.btn_remove_trnsctn.setText(_translate("glav", "Удалить"))
