# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log(object):
    def setupUi(self, log):
        log.setObjectName("log")
        log.resize(800, 600)
        log.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.centralwidget = QtWidgets.QWidget(log)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 471, 131))
        self.label_2.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 25pt \"MV Boli\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.reg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reg_btn.setGeometry(QtCore.QRect(240, 390, 321, 71))
        self.reg_btn.setStyleSheet("QPushButton {\n"
"color: rgb(255, 85, 255);\n"
"background-color: rgb(0, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid rgb(200, 0, 245);\n"
"border-radius: 7px;\n"
"width: 200 px;\n"
"height: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(5, 251, 255, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0, 255, 255, 65);\n"
"}")
        self.reg_btn.setObjectName("reg_btn")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(330, 230, 141, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.password_save = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password_save.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.password_save.setObjectName("password_save")
        self.gridLayout.addWidget(self.password_save, 3, 0, 1, 1)
        self.name_save = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name_save.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.name_save.setObjectName("name_save")
        self.gridLayout.addWidget(self.name_save, 0, 0, 1, 1)
        log.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(log)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        log.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(log)
        self.statusbar.setObjectName("statusbar")
        log.setStatusBar(self.statusbar)

        self.retranslateUi(log)
        QtCore.QMetaObject.connectSlotsByName(log)

    def retranslateUi(self, log):
        _translate = QtCore.QCoreApplication.translate
        log.setWindowTitle(_translate("log", "SIGNUP"))
        self.label_2.setText(_translate("log", "Регистрация"))
        self.reg_btn.setText(_translate("log", "Авторизоваться"))
        self.password_save.setPlaceholderText(_translate("log", "Пароль:"))
        self.name_save.setPlaceholderText(_translate("log", "Имя:"))
